sudo python test_with_time.py --prototxt "PROTOTXTs/vgg-16-encoder-decoder-contour-pascal-test.prototxt" --caffemodel "../models_old/CEDN-PASCAL-dRdGdB-WEIGTH_FIXED_INITIALIZATION_NO_TRAIN/caffe/vgg-16-encoder-decoder-contour-w10-pascal-iter005.caffemodel" --imnames "../data/PASCAL/val.txt" --intput "../data/PASCAL/JPEGImages" --output "../results/CEDN-PASCAL-dRdGdB-WEIGTH_FIXED_INITIALIZATION_NO_TRAIN/CEDN-PASCAL-05-dRdGdB-WEIGTH_FIXED_INITIALIZATION_NO_TRAIN" --color "RGB"

sudo python test_with_time.py --prototxt "PROTOTXTs/vgg-16-encoder-decoder-contour-pascal-test.prototxt" --caffemodel "../models_old/CEDN-PASCAL-dRdGdB-WEIGTH_FIXED_INITIALIZATION_NO_TRAIN/caffe/vgg-16-encoder-decoder-contour-w10-pascal-iter005.caffemodel" --imnames "../data/PASCAL/val.txt" --intput "../data/PASCAL/JPEGImages" --output "../results/CEDN-PASCAL-dRdGdB-WEIGTH_FIXED_INITIALIZATION_NO_TRAIN/CEDN-PASCAL-05-dRdGdB-WEIGTH_FIXED_INITIALIZATION_NO_TRAIN" --color "LAB"

sudo python test_with_time.py --prototxt "PROTOTXTs/vgg-16-encoder-decoder-contour-pascal-test.prototxt" --caffemodel "../models_old/CEDN-PASCAL-dRdGdB-WEIGTH_FIXED_INITIALIZATION_NO_TRAIN/caffe/vgg-16-encoder-decoder-contour-w10-pascal-iter005.caffemodel" --imnames "../data/PASCAL/val.txt" --intput "../data/PASCAL/JPEGImages" --output "../results/CEDN-PASCAL-dRdGdB-WEIGTH_FIXED_INITIALIZATION_NO_TRAIN/CEDN-PASCAL-05-dRdGdB-WEIGTH_FIXED_INITIALIZATION_NO_TRAIN" --color "LUV"

sudo python test_with_time.py --prototxt "PROTOTXTs/vgg-16-encoder-decoder-contour-pascal-test.prototxt" --caffemodel "../models_old/CEDN-PASCAL-dRdGdB-WEIGTH_FIXED_INITIALIZATION_NO_TRAIN/caffe/vgg-16-encoder-decoder-contour-w10-pascal-iter005.caffemodel" --imnames "../data/PASCAL/val.txt" --intput "../data/PASCAL/JPEGImages" --output "../results/CEDN-PASCAL-dRdGdB-WEIGTH_FIXED_INITIALIZATION_NO_TRAIN/CEDN-PASCAL-05-dRdGdB-WEIGTH_FIXED_INITIALIZATION_NO_TRAIN" --color "HSV"

sudo python test_with_time.py --prototxt "PROTOTXTs/vgg-16-encoder-decoder-contour-pascal-test.prototxt" --caffemodel "../models_old/CEDN-PASCAL-dRdGdB-WEIGTH_FIXED_INITIALIZATION_NO_TRAIN/caffe/vgg-16-encoder-decoder-contour-w10-pascal-iter005.caffemodel" --imnames "../data/PASCAL/val.txt" --intput "../data/PASCAL/JPEGImages" --output "../results/CEDN-PASCAL-dRdGdB-WEIGTH_FIXED_INITIALIZATION_NO_TRAIN/CEDN-PASCAL-05-dRdGdB-WEIGTH_FIXED_INITIALIZATION_NO_TRAIN" --color "YO1O2"

sudo python test_with_time.py --prototxt "PROTOTXTs/vgg-16-encoder-decoder-contour-pascal-test.prototxt" --caffemodel "../models_old/CEDN-PASCAL-dRdGdB-WEIGTH_FIXED_INITIALIZATION_NO_TRAIN/caffe/vgg-16-encoder-decoder-contour-w10-pascal-iter005.caffemodel" --imnames "../data/PASCAL/val.txt" --intput "../data/PASCAL/JPEGImages" --output "../results/CEDN-PASCAL-dRdGdB-WEIGTH_FIXED_INITIALIZATION_NO_TRAIN/CEDN-PASCAL-05-dRdGdB-WEIGTH_FIXED_INITIALIZATION_NO_TRAIN" --color "dRdGdB"
